[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",]


[invariant]
runs = 5
depth = 5
fail_on_revert = false

